"""change table status

Revision ID: 1055116bf7a5
Revises: 21d1705d3b98
Create Date: 2026-03-01 06:43:45.870961

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1055116bf7a5"
down_revision: Union[str, Sequence[str], None] = "21d1705d3b98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
