"""change table status

Revision ID: 56704b67437b
Revises: dda04903e2ff
Create Date: 2026-03-01 07:15:47.510591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56704b67437b"
down_revision: Union[str, Sequence[str], None] = "dda04903e2ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dining_table",
        "status",
        existing_type=postgresql.ENUM(
            "free", "occupied", "reserved", name="table_status"
        ),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'free'::table_status"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dining_table",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM("free", "occupied", "reserved", name="table_status"),
        nullable=False,
        existing_server_default=sa.text("'free'::table_status"),
    )
    # ### end Alembic commands ###
