"""cange menuitem

Revision ID: 5fd915fc3aae
Revises: cab03a54465a
Create Date: 2026-02-25 12:11:58.526095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fd915fc3aae"
down_revision: Union[str, Sequence[str], None] = "cab03a54465a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "menu_item", "category_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "menu_item", "category_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
