"""change  tables and create media

Revision ID: cab03a54465a
Revises: ebdb6e43a011
Create Date: 2026-02-25 10:25:11.011444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cab03a54465a"
down_revision: Union[str, Sequence[str], None] = "ebdb6e43a011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("menu_item", sa.Column("img_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        None, "menu_item", "media", ["img_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("users", sa.Column("avatar_id", sa.BigInteger(), nullable=True))
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key(
        None, "users", "media", ["avatar_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "avatar_id")
    op.drop_constraint(None, "menu_item", type_="foreignkey")
    op.drop_column("menu_item", "img_id")
    op.drop_table("media")
    # ### end Alembic commands ###
