"""cange menucategory

Revision ID: e24142c81f3a
Revises: 5fd915fc3aae
Create Date: 2026-02-25 12:51:15.909865

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e24142c81f3a"
down_revision: Union[str, Sequence[str], None] = "5fd915fc3aae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
